Cargo.lock
Cargo.toml
README.md
src/actors/jsonrpc_server.rs
src/actors/mod.rs
src/actors/tcp_server.rs
src/error.rs
src/main.rs

JSON-RPC provides a means of exposing a user interface for the `solar` node. This means that MUXRPC is only used for node-to-node interactions (primarily replication).
**Why websockets?**
Can be queried natively and in-browser without much hassle.
**Why https://crates.io/crates/jsonrpc-ws-server and not https://crates.io/crates/jsonrpsee-ws-server?**
`jsonrpsee` is based on the `tokio` runtime. Since `solar` is based on `async_std`, this means we would have to run two async runtimes during the execution of `solar`. I deem this to be an unacceptable resource burden. `jsonrpc-ws-server` is synchronous and lightweight.
-----
This PR introduces a new JSON-RPC actor with two endpoints: `ping` and `whoami`. It shuts down gracefully when a termination signal is received from the broker. More …

Add JSON-RPC server

---

src/actors/jsonrpc_server.rs
src/actors/lan_discovery.rs
src/actors/peer.rs
src/actors/rpc/blobs_get.rs
src/actors/rpc/blobs_wants.rs
src/actors/rpc/get.rs
src/actors/rpc/handler.rs
src/actors/rpc/history_stream.rs
src/actors/rpc/whoami.rs
src/actors/tcp_server.rs
src/broker.rs
src/config.rs
src/main.rs
src/storage/blob.rs
src/storage/kv.rs

No change in functionality; just some gardening.
- Remove all `extern` statements from `src/main.rs`
- Replace them with `use` statements where required
- Group `use` statements under the root dependency
- Organise `use` statements in the following order
- `std::`
- All external dependencies (in alphabetical order)
- `crate::`

Remove extern statements and standardise use statements

---

README.md
src/actors/rpc/history_stream.rs
src/config.rs
src/main.rs

🚨  **BREAKING CHANGES INTRODUCED** 🚨 
This PR takes the existing solar config file (`solar.toml`) and splits it into two files. One for the public-private keypair (`secret.toml`) and one for replication configuration (`replication.toml`).
This separation of concerns is in keeping with Scuttlebutt tradition. It also means that replication configuration can be shared without risk of exposing the public-private keypair.
The replication configuration file currently only contains a list of public keys of peers who should be replication. In the future it may hold additional replication settings.
I have also taken this opportunity to rename the `friends` CLI option to `replicate`. "Friends" has a very specific meaning in the context of Scuttlebutt (a mutual follow) and I don't want to cause …

Split config file and rename "friends" option

---

README.md
src/actors/jsonrpc_server.rs
src/storage/kv.rs

Adds the ability to store and query the public key and latest sequence number of all feeds in the local database. I think this will be really useful for testing replication. Basically corresponds to the `replicate.upto` MUXRPC method in go-ssb.
- Adds a peer prefix
- Adds kv store methods
- `peer_key`
- `set_peer`
- `get_peers`
- Adds a JSON-RPC method
- `get_peers`
I'm not too sure about the `get_peers` naming. Might change it later as the API grows.
Example JSON-RPC response (pretty printed):
```
{
"id": 1,
"jsonrpc": "2.0",
"result": [
{
"id": "@4+aQ4kCvSvghIq2yTh6LPz0ELZ3x4CKd93JTwkoudPM=.ed25519",
"sequence": 48
},
{
"id": "@HEqy940T6uB+T+d9Jaa58aNfRzLx9eRWqkZljBmnkmk=.ed25519",
"sequence": 25179
},
{
"id": "@MDErHCTxklXc7QZ43fnyzERbRJ7fccRfCYF11EqIFEI=.ed25519",
"sequence": 3
},
{ …
```

Query peers in db

---

src/actors/jsonrpc_server.rs
src/actors/rpc/get.rs
src/actors/rpc/history_stream.rs
src/storage/kv.rs

The major change in this PR is to the naming scheme for methods, variables and types.
Kuska code refers to a Scuttlebutt message in the form of a KVT (Key Value Timestamp) as a "feed". This has been a source of much confusion to me, coming from development in other Scuttlebutt codebases where a feed refers to a sequence of interconnected messages authored by a single keypair. The feed is the collection of messages, never a single message. Messages are now referred to as either message values (just the V in KVT) or message KVTs in the database code.
Documentation coverage has also been significantly improved for the KV store.
Finally, actors which utilise methods from `kv.rs` have also been updated to reflect the revised naming scheme.

Refactor KV store

---

src/actors/jsonrpc_server.rs
src/error.rs
src/storage/kv.rs

`src/storage/kv.rs` was the outlier in the codebase, in that it was the only module to implement a custom error type. This PR removes that and adds the necessary variants to the crate-level error type.
Variant names have been changed with the goal of enhancing clarity. The display implementation has also been refactored to describe the general error for each variant (using all lowercase without any trailing punctuation).
A few small changes have been made in `src/actors/jsonrpc_server.rs` to accommodate the error changes.

Remove KV error type and refactor error variants

---

src/actors/rpc/handler.rs
src/actors/rpc/history_stream.rs
src/storage/kv.rs

Another PR aimed at improving grokability of the codebase.
The legacy replication logic should be a lot easier to follow now.

Add code and doc comments to the history stream module

---

Cargo.lock
src/actors/rpc/history_stream.rs
src/storage/kv.rs

This PR increases test coverage for the primary key-value database (`src/storage/kv.rs`).
It tests the following methods:
- `append_feed(msg)`
- `get_latest_msg_val(&keypair.id)`
- `get_latest_seq(&keypair.id)`
- `get_msg_kvt(&keypair.id, 2)`
- `get_msg_val(&keypair.id, 2)`
- `set_peer(peer_key, peer_seq)`
- `get_peers(peer_key, peer_seq)`

Add KV tests

---

README.md
src/actors/jsonrpc_server.rs

Minor changes:
- `get_peers` becomes `peers`
- `seq` becomes `seq_num` in `publish` response
- README updates
Still unsure about API conventions for the JSON-RPC endpoints but for now I'm going with the following:
- No `get_` prefix for getters (same as Rust API conventions)
- Setters begin with a verb (e.g. `publish`)
- Request and response fields should have consistent naming (ie. `seq_num` throughout, instead of mixing `seq`, `seq_num` and `sequence`)

Rename get_peers JSON-RPC method

---

README.md
src/actors/jsonrpc_server.rs

Exposes a JSON-RPC endpoint for returning the message KVT identified by the given key (sha256 hash).
Returns `null` if the message is not found.
Example output:
```shell
{
"id": 1,
"jsonrpc": "2.0",
"result": {
"key": "%AeqDvXMLRRJoeoPspbZoCcr2Pz1KV4ai2w31If6JFag=.sha256",
"rts": null,
"timestamp": 1671187420.5955684,
"value": {
"author": "@MDErHCTxklXc7QZ43fnyzERbRJ7fccRfCYF11EqIFEI=.ed25519",
"content": {
"text": "Now playing: HARU NEMURI - Shunka Ryougen (2022)",
"type": "post"
},
"hash": "sha256",
"previous": "%UIIoYlRaQKp5gG62hccnhCGnBODh2gXRdNfpPTKvwko=.sha256",
"sequence": 11,
"signature": "vQa8QS/lJ9dKbsn3sZCegYhL1L67iNEFa/LuCw39raJKxOhvbNs9kerGeFCkw1iOhKGpBq9BZYwojWGBIZUWDA==.sig.ed25519",
"timestamp": 1671187420592
}
}
}
```

Add message jsonrpc method

---

README.md
src/actors/jsonrpc_server.rs
src/storage/kv.rs

_The dominoes are falling swiftly._
Exposes a JSON-RPC endpoint for returning all messages (as KVTs) comprising the feed identified by the give public key (`ed25519`).
Returns an array of messages in ascending order.

Add feed jsonrpc method

---

README.md
src/actors/rpc/history_stream.rs
src/main.rs

This PR reintroduces the local feed resync option via a CLI flag. Resync defaults to `false` if unset.
I am seeing broken pipe errors for blob get / wants in the logs but only on initial resync. I'm going to look into blobs support more closely to see if we can handle that more gracefully (and maybe not break pipes unnecessarily to begin with).
Small `README` updates have also been introduced:
- Include printout of the CLI help menu
- Add link to RPi build instructions
- Remove documentation todo section
Addresses https://github.com/mycognosist/solar/issues/31

Expose resync option

---

src/actors/jsonrpc_server.rs
src/actors/rpc/history_stream.rs
src/cli.rs
src/config.rs
src/main.rs

Application configuration is now grouped in the same module as replication configuration and secret configuration. This results in a much quieter main module (`src/main.rs`), which is now mainly concerned with triggering application configuration, opening the key-value stores for writing, spawning actors and starting the message loop.
- Move CLI generator and parser into a separate module (`src/cli.rs`)
- Move application configuration into config module (`src/config.rs`)

Split CLI and application config from main

---

README.md
src/actors/lan_discovery.rs
src/actors/peer.rs
src/actors/tcp_server.rs
src/cli.rs
src/config.rs
src/main.rs

Solar already exhibits selective outbound peering and replication: it will only call out to peers who are listed in `replication.toml` (and peer addresses passed in with the `--connect` CLI flag are automatically written to `replication.toml`).
This PR adds selective inbound peering and replication as default. If a peer connects to the local instance but is not listed in `replication.toml`, the connection will be dropped once the secret handshake is complete (required to learn the public key of the caller).
The nonselective replication can be enabled by passing the `--selective false` CLI option.
Sooner or later I need to think about the configuration structure carefully (ie. what is exposed as an env var, a CLI flag or a value in a config file on disk).

Filter inbound peer connections

---

README.md
src/actors/peer.rs
src/actors/rpc/history_stream.rs
src/config.rs
src/main.rs

This PR adds support for specifying peer connection data in `replication.toml`, in the form of a URL. 
See https://github.com/mycognosist/solar/pull/40 and https://github.com/mycognosist/solar/issues/12 for additional context.
The `replication.toml` configuration file now takes the following form:
```toml
[peers]
"@o8lWpyLeSqV/BJV9pbxFhKpwm6Lw5k+sqexYK+zT9Tc=.ed25519" = "tcp://[200:9730:17c:7f5b:c7c6:c999:7b2a:c958]:8008"
"@HEqy940T6uB+T+d9Jaa58aNfRzLx9eRWqkZljBmnkmk=.ed25519" = ""
```
This is another baby step on the path to implementing a connection manager.

Update peer replication config to use URLs

---

README.md
src/config.rs

Improves consistency of environment variable naming.
`SLED_CACHE_CAPACITY` -> `SOLAR_KV_CACHE_CAPACITY`
Also removes two lines of commented code that snuck into `src/config.rs`.

Rename sled cache capacity env var

---

.github/workflows/rust.yml
src/actors/lan_discovery.rs
src/actors/peer.rs
src/actors/rpc/get.rs
src/broker.rs
src/config.rs
src/error.rs
src/storage/blob.rs
src/storage/kv.rs

probably a typo? before, the `feed` RPC would return all messages *except* the last one. Noticed when a `publish` call returned an unexpected sequence number.

fix: return full feed including last message

---

src/actors/connection_manager.rs
src/actors/mod.rs
src/actors/peer.rs
src/actors/rpc/history_stream.rs
src/actors/tcp_server.rs
src/main.rs
src/storage/kv.rs

See https://github.com/mycognosist/solar/issues/12 for thoughts.
Each new connection is registered with the manager and assigned an ID.
Right now the manager is primarily a connection logger; it listens for `ConnectionEvent` messages on the message bus and logs the events (along with the connection ID). The events themselves are published from the `peer` actor.
I'm aiming to slowly separate connection and replication concerns so that the `peer` actor is only concerned with handshaking and replication. The final separation might look like: 1) connection manager, 2) connection scheduler, 3) connection handler, 4) replication (the `peer` actor).
I have also introduced an idle timeout for peer connections. I noticed during testing that it's possible to get stuck in the replication loop …

Add a minimal connection manager

---

Cargo.lock
Cargo.toml
src/actors/jsonrpc_server.rs
src/actors/tcp_server.rs
src/error.rs

This is a fairly straightforward replacement of one JSON-RPC library with another (`jsonrpc-http-server` -> `jsonrpsee`).
The change fixes a bug which blocked TCP connections. See https://github.com/mycognosist/solar/issues/50 for more details.

Replace JSON-RPC crate with async equivalent

---

Cargo.lock
Cargo.toml

Removes `procfs`, `slice-deque` and `snap`. Moves `tempdir` into `dev-dependencies`.
https://github.com/mycognosist/solar/issues/54

Remove unused dependencies and update lockfile

---

solar/src/config.rs

This took me a little while to figure out and it was mostly because there's literally no feedback at all whe I pass a bad value. Example calls to try this with:
```terminal
cargo run -- --connect 'tcp://::1:8080?shs=O4CiyVLNWz6FgU3aTJEUo398O8k9GmEpCXEdriib9MI=.ed25519'
cargo run -- --connect 'tcp://[::1]:8080?shs=O4CiyVLNWz6FgU3aTJEUo398O8k9GmEpCXEdriib9MI=.ed25519'
```

Print more informative error message when user passes bad arguments

---

.github/workflows/rust.yml

This PR simply updates the CI workflows to target the `main` branch instead of `master`.
Once this PR is merged I'll update the repo to point to `main` as the primary branch.

Rename master to main

---

solar/README.md
solar/src/actors/muxrpc/history_stream.rs
solar/src/actors/network/config.rs
solar/src/actors/network/connection_manager.rs
solar/src/actors/network/connection_scheduler.rs
solar/src/actors/network/mod.rs
solar/src/actors/network/secret_handshake.rs
solar/src/actors/replication/classic.rs
solar/src/actors/replication/config.rs
solar/src/config.rs
solar/src/error.rs
solar/src/node.rs
solar_cli/src/main.rs

Addresses https://github.com/mycognosist/solar/issues/63
The main addition of the PR is the connection scheduler module. I've chosen to begin with a very simple implementation. The flow is as follows:
- Combine the list of peers to be dialed from `replication.toml` and `--connect` (CLI) into a single vector
- Spawn the connection scheduler actor, passing in the list of peers to be dialed
- Place all peers to be dialed into an "eager" queue
- Pull one peer from the eager queue every 5 seconds and attempt a connection
- If the connection fails, push the peer to the "lazy" queue
- If the connection succeeds, push the peer back to the eager queue
- Pull one peer from the lazy queue every 60 seconds and attempt a connection
I've introduced the `ConnectionData` `struct` in the connection …

Add a basic connection scheduler

---

Cargo.lock
README.md
solar/Cargo.toml
solar/README.md
solar/src/actors/muxrpc/history_stream.rs
solar/src/actors/network/connection.rs
solar/src/actors/replication/config.rs
solar/src/config.rs
solar/src/error.rs
solar/src/node.rs
solar/src/secret_config.rs
solar_cli/src/main.rs

Addresses https://github.com/mycognosist/solar/issues/69
There were a few bugs bundled together in this one.
I ended up changing the `peers` field of `ReplicationConfig` to be a `HashMap<String, String>` (rather than `HashMap<PublicKey, String>`). This makes deserialization far simpler. I've added a validation method on `ReplicationConfig` which is run after the data is deserialized from file. The validation performs a simple check of the peer address and comprehensive checks of the public key.
I also noticed that I was erroneously overwriting the peers replication field with an empty `HashMap` in `solar_cli/src/main.rs` (woops). That's fixed now.

Fix replication configuration parsing from TOML file

---

solar/src/actors/network/connection_scheduler.rs

A small change to the API of the connection scheduler.
Instead of having to call `ConnectionScheduler::new()` with a `Vec` of `(PublicKey, String)`, peers can now be added and removed via the new `add_peer` and `remove_peer` methods after the default instance of the connection scheduler has been created. This has the advantage of allowing peers to be added and removed from the scheduler throughout the node's operation (for example, through messages sent via the broker and acted upon in the message loop of the scheduler).

Add `add_peer` and `remove_peer` methods to connection scheduler

---

solar/src/actors/network/connection.rs
solar/src/actors/network/connection_scheduler.rs
solar/src/actors/network/dialer.rs
solar/src/actors/network/lan_discovery.rs
solar/src/actors/network/mod.rs
solar/src/node.rs

This PR introduces the `dialer` actor module which listens for `DialRequest` messages emitted by the connection scheduler and dials peers accordingly.
The `DialRequest` messages currently include the public key and address of the peer to be dialed. In the next iteration, the address requirement will be removed. Instead, the dialer will receive the `DialRequest` message and use the public key of the peer to query the corresponding address from the address book. 
Related to https://github.com/mycognosist/solar/issues/72

Extract dialer from scheduler

---

README.md
solar/README.md
solar/src/actors/muxrpc/history_stream.rs
solar/src/error.rs
solar/src/storage/indexes.rs
solar/src/storage/kv.rs
solar/src/storage/mod.rs

This PR is the result of an exploration into database indexes for common SSB message content types and data. While I initially felt that it might be best to keep index creation separate from `solar`, I realise that such an approach will likely decrease the chance of others using the software to develop their own client. If this turns out to be a bad idea, at least the `index` module is sufficiently encapsulated and can easily be split-off.
Each message is indexed immediately after having been appended to the database.
A next step would be to expose the index getter methods via JSON-RPC. It may also be worthwhile to consider approaches for validating, wiping / resetting and reindexing.
```rust
get_blocks(ssb_id)
get_blockers(ssb_id)
get_channel_subscribers(channel) …
```

Add basic message content indexes

---

Cargo.lock
solar/src/actors/muxrpc/blobs_get.rs
solar/src/actors/muxrpc/blobs_wants.rs
solar/src/actors/muxrpc/history_stream.rs
solar/src/actors/muxrpc/mod.rs
solar/src/actors/network/connection.rs
solar/src/actors/network/connection_manager.rs
solar/src/actors/network/connection_scheduler.rs
solar/src/actors/network/dialer.rs
solar/src/actors/replication/classic.rs
solar/src/broker.rs
solar/src/storage/blob.rs
solar/src/storage/kv.rs

The primary change introduced in this PR is the conversion of `BrokerMessage` from a generic definition (`Arc<dyn Any + Send + Sync>`) to an `enum`. While the generic approach is convenient, it requires the message to be downcast each time a match occurs - usually as a reference. The change allows for more compact matching and should also open the door for a refactor of the connection and replication flow (more to come on that in a future PR).
Other minor changes:
- Replace single variant enums with tuple structs
- Variable renaming (ie. `StoBlobEvent` -> `StoreBlobEvent` etc.)
- Replace `*` imports with explicit imports (from `broker` module)

Replace generic broker message type with enum

---

Cargo.lock
solar/Cargo.toml
solar/src/actors/muxrpc/history_stream.rs
solar/src/actors/network/connection.rs
solar/src/actors/network/connection_manager.rs
solar/src/actors/network/connection_scheduler.rs
solar/src/actors/replication/classic.rs
solar/src/broker.rs
solar/src/error.rs
solar/src/storage/kv.rs
solar_cli/Cargo.toml

This PR introduces a major refactor of the TCP connection life-cycle handling.
Connection data (including the TCP stream) is now passed to the connection manager and each phase of the cycle is handled there. This deviates from the previous approach where data was passed between various methods and the connection manager was mostly playing the role of registering connections and logging the steps. The connection life-cycle should now be easier to follow.
The refactor was prompted by my early explorations into adding EBT support. I soon realised that I needed to be able to take ownership of the stream in order to run an EBT loop.
Replication has been successfully tested between two `solar` instances and a `solar` and `Patchwork` instance.

Event driven connections with message passing

---

solar/src/actors/muxrpc/blobs_get.rs
solar/src/actors/muxrpc/history_stream.rs
solar/src/actors/replication/blobs.rs
solar/src/actors/replication/ebt/manager.rs
solar/src/actors/replication/mod.rs

- Move the blob reference extraction code out of `history_stream` and into the `blobs` replication module
- Extract blob references from messages received via EBT
- Call `"blob, get"` for any extracted references that are not already available locally

Request blobs from EBT msgs

---

solar/src/actors/muxrpc/ebt.rs
solar/src/actors/muxrpc/history_stream.rs
solar/src/actors/replication/ebt/manager.rs
solar/src/storage/kv.rs

Listen for `StoreKvEvent`, indicating that a message has been appended to a feed in the local key-value store; retrieve the latest sequence number for the feed and send a partial vector clock for that feed to all active EBT sessions. This allows us to notify peers of changes to our replication state.
This PR also removes a redundant check for vector clocks in received MUXRPC requests.

Send partial vector clock when local KV store is updated

---

solar/src/actors/replication/ebt/manager.rs
solar/src/config.rs
solar/src/node.rs

Following the same approach taken by `ssb-ebt` (used in Manyverse), we persist peer vector clocks to the `ebt` directory in the application's root configuration directory (`~/.local/share/solar` in the case of solar).
Each file is created using the @-prefixed SSB ID of the author as the filename; all instances of `/` are replaced with `-` and the `=` before `.ed25519` is removed. For example: `@HIYqoOhH6U-muCXsnvXzRQmoPpPXrELnJlqSjId2Fg8.ed25519`
The file then contains a JSON string of the vector clock for that peer. For example: `{"@HIYqoOhH6U+muCXsnvXzRQmoPpPXrELnJlqSjId2Fg8=.ed25519":32,"@HZnU6wM+F17J0RSLXP05x3Lag2jGv3F3LzHMjh72coE=.ed25519":7712}`
Clocks are loaded from file when the EBT manager starts and persisted to file just before it shuts down.

Load and persist peer vector clocks

---

solar/src/actors/muxrpc/ebt.rs
solar/src/actors/replication/ebt/manager.rs

This PR reintroduces deserialization code for vector clocks in MUXRPC responses, which had previously been erroneously considered redundant and removed, and uses negative request numbers in EBT-related MUXRPC responses.
Bidirectional replication is now working; tested between solar and Manyverse, and solar and Patchwork.
Note that live outbound updates from solar are not yet working. In other words, if you have an active EBT session and the local store of solar is updated - new messages of interest are not automatically sent out to connected peers. Instead, only a partial vector clock is sent. I am going to work on the live message sending next.
CC: @black-puppydog

Match on vector clock response and use negative request numbers

---

solar/src/actors/muxrpc/ebt.rs
solar/src/actors/network/connection.rs
solar/src/actors/replication/ebt/manager.rs
solar/src/actors/replication/ebt/replicator.rs

Active EBT sessions were previously tracked primarily using the request ID. This becomes problematic when multiple EBT sessions are active at the same time, since every peer starts with request number 1. Since each new connection is assigned a unique ID, this provides a natural mechanism for more accurately associating session events with a given peer.
The connection ID is now included in `SendMessage` and `SendClock` events. The MUXRPC EBT handler, upon receiving such an event, can then compare the connection ID against the connection ID it was invoked with - acting only if the two match. Other running instances of the handler will simply ignore those events which were not intended for them.
Session tracking still needs more work but there are steps in the right direction.
This PR is …

Improved EBT session tracking

---

solar/src/actors/muxrpc/history_stream.rs
solar/src/actors/replication/ebt/manager.rs
solar/src/storage/kv.rs

While testing EBT I noticed that Manyverse sends messages of interest to active session peers immediately, instead of sending a partial vector clock indicating the update. This PR introduces that same behaviour to solar.
An event is emitted when the local key-value store is updated with a new message. The event includes the feed ID and the sequence number of the appended message. Those details are matched on in the EBT manager. If we have an active session with a peer interested in receiving messages from that feed, we send the message (as long as the sequence number is greater than the sequence number in the latest vector clock from that peer).
Live updates are now bidirectional when an EBT session is active between solar and Manyverse, as well as between two instances of solar.

Introduce live message sending for EBT sessions

---

solar/src/actors/muxrpc/ebt.rs
solar/src/actors/replication/ebt/manager.rs
solar/src/actors/replication/ebt/replicator.rs

This behaviour is not spec'd out for EBT so I'm simply following the defined behaviour for classic replication streams.
When `solar` receives a termination signal, any active EBT session peers are sent an RPC message with both the stream and end/err flags set and a JSON body of `true`. Upon receiving such a request, a `solar` peer will send one in response (this is probably unnecessary but seems like good practice nonetheless).
Manyverse does not appear to implement this behaviour; no end-of-stream RPC message is received when terminating Manyverse during an active session (at least not that I can detect). I would much rather have explicit communication in this case.

Send end-of-stream request to all active sessions before solar terminates

---

README.md
solar/src/actors/jsonrpc/server.rs

While working on https://github.com/mycognosist/solar/pull/94 I realised the shape of the parameters for many of the methods were not spec-compliant. They must either be an array or a map. I've converted the methods which expected a string to instead expect an array of string; this ends up being a simpler implementation that using maps.

Fix JSON-RPC server params

---

Cargo.lock
Cargo.toml
README.md
solar/README.md
solar/src/actors/jsonrpc/server.rs
solar/src/storage/indexes.rs
solar/src/storage/kv.rs
solar_client/Cargo.toml
solar_client/README.md
solar_client/examples/blocks.rs
solar_client/examples/descriptions.rs
solar_client/examples/feed.rs
solar_client/examples/follows.rs
solar_client/examples/images.rs
solar_client/examples/is_following.rs
solar_client/examples/latest_description.rs
solar_client/examples/latest_image.rs
solar_client/examples/latest_self_description.rs
solar_client/examples/message.rs
solar_client/examples/names.rs
solar_client/examples/peers.rs
solar_client/examples/ping.rs
solar_client/examples/publish.rs
solar_client/examples/self_descriptions.rs
solar_client/examples/self_images.rs
solar_client/examples/subscribers.rs
solar_client/examples/subscriptions.rs
solar_client/examples/whoami.rs
solar_client/src/lib.rs

Now that EBT is working reliably, I'm focusing on making it easier to interact with `solar` in an application context. I think the addition of a JSON-RPC client library will be a significant step forward.
**API**

Add a JSON-RPC client library
